Aave Funding Proposal
bgd-labs/aave-proposals-v3 pull request #230
Opened 2024-03-01 23:38 UTC by efecarranza

# Notes Compared to Post

1.5 M USDT from Aave V3 cannot be withdrawn, withdrawing 1.2M
Aave V3 LUSD is paused

# Changelog

Add proposal to fund Aave for the upcoming months.
Add Tests.
Add AIP.

2024-03-02 19:31 UTC, sakulstra requested changes
reminder for me

2024-03-06 13:03 UTC, sakulstra commented on src/20240224_Multi_FundingUpdate/AaveV3Ethereum_FundingUpdate_20240224.sol
> +  function _swap() internal {
imo this whole functions is a bit messy:
- transfer & withdraw v3 manually
- transfer & withdraw & swap v2/v3 mix
- swap remaining v3

I think a bit cleaner to review would be:
`_withdrawV2Tokens` -> withdraw v2 tokens to SWAPPER
`_withdrawV3Tokens` -> withdraw v3 tokens to SWAPPER
manually initiate the swaps (as there's no clean way to do `unique` over two arrays.

2024-03-06 13:20 UTC, efecarranza commented on src/20240224_Multi_FundingUpdate/AaveV3Ethereum_FundingUpdate_20240224.sol
> +    AaveV3Ethereum.COLLECTOR.approve(
removed

2024-03-06 20:32 UTC, rustboyar approved these changes

2024-03-06 21:41 UTC, sakulstra commented on src/20240224_Multi_FundingUpdate/AaveV3Ethereum_FundingUpdate_20240224.sol
> +
```suggestion
```

2024-03-06 21:41 UTC, sakulstra commented on src/20240224_Multi_FundingUpdate/AaveV3Ethereum_FundingUpdate_20240224.sol
> +  function _withdrawV3Tokens() internal {
```suggestion
  function _withdrawV3Tokens() internal {
    uint256 rawUSDTBalance = IERC20(AaveV3EthereumAssets.USDT_UNDERLYING).balanceOf(address(AaveV3Ethereum.COLLECTOR));
    AaveV3Ethereum.COLLECTOR.transfer(
      AaveV3EthereumAssets.USDT_UNDERLYING,
      address(SWAPPER),
      rawUSDTBalance
    );
```

2024-03-07 08:40 UTC, sakulstra approved these changes

2024-03-07 09:06 UTC, rustboyar approved these changes

2024-03-07 09:08 UTC, merged