Ethereum v2 Reserve Factor Adjustment Mar 2024
bgd-labs/aave-proposals-v3 pull request #258
Opened 2024-03-20 13:21 UTC by defijesus

2024-03-20 14:48 UTC, efecarranza requested changes

2024-03-20 14:48 UTC, efecarranza commented on src/20240320_AaveV2Ethereum_EthereumV2ReserveFactorAdjustment/AaveV2Ethereum_EthereumV2ReserveFactorAdjustment_20240320.sol
> +  uint256 public constant WBTC_RF = 30_00;
I think this should be 40?

2024-03-20 14:48 UTC, efecarranza commented on src/20240320_AaveV2Ethereum_EthereumV2ReserveFactorAdjustment/EthereumV2ReserveFactorAdjustment.md
> +his AIP is a continuation of proposal 49 on Governance v3 and increases the Reserve Factor (RF) for assets on Ethereum v2 by 5.00%, up to a maximum of 99.99%.
This*

2024-03-21 12:53 UTC, brotherlymite commented on src/20240320_AaveV2Ethereum_EthereumV2ReserveFactorAdjustment/EthereumV2ReserveFactorAdjustment.md
> +| DAI   | 25.00%                  | 30.00%             |
DAI reserve factor is already at 30%, updated by this [AIP](https://vote.onaave.com/proposal/?proposalId=49&ipfsHash=0xd0254523d65549ea7d020d91df2b7905a27da988ecc8263f2cf2709c2e369cc7)

Do you wish to update it to 35%?

2024-03-25 14:05 UTC, brotherlymite approved these changes

2024-03-25 14:06 UTC, eboadom approved these changes

2024-03-25 14:08 UTC, merged