Chaos Labs Engagement Amendment 20240415
bgd-labs/aave-proposals-v3 pull request #305
Opened 2024-04-18 12:27 UTC by eyalovadya

Discussion: https://governance.aave.com/t/arfc-chaos-labs-engagement-amendment/17324

2024-04-19 06:44 UTC, sakulstra commented on src/20240415_AaveV3Ethereum_ChaosLabsEngagementAmendment/AaveV3Ethereum_ChaosLabsEngagementAmendment_20240415.sol
> +
```suggestion
  uint256 public constant ACTUAL_STREAM_AMOUNT =
    (STREAM_AMOUNT_GHO / STREAM_DURATION) * STREAM_DURATION;
    
```

stream amount should always be fully claimable, therefore the amount must be exactly divisible by emissionPerSecond

the final amount will be a few wei less due to rounding: `399999999999999997440000`

2024-04-19 06:44 UTC, sakulstra commented on src/20240415_AaveV3Ethereum_ChaosLabsEngagementAmendment/AaveV3Ethereum_ChaosLabsEngagementAmendment_20240415.sol
> +      STREAM_AMOUNT_GHO,
```suggestion
      ACTUAL_STREAM_AMOUNT,
```

2024-04-19 07:07 UTC, sakulstra requested changes
Overall it#s looking okay, but it could be better:

1. the amount should always be a multiple of emissionPerSecond to have no unclaimable dust remaining in streams. So what all the other proposals do is sth like: `uint256 exactAmount = (amount/duration) * duration;`

2. the duration on the proposal is a bit arbitrary set to 200 days, which will be slightly longer/shorter then your current streams, but for sure not end at the same time. As you know when your current stream ends you can do it exact actually.

Therefore my suggestion would be to do the following:
```
  uint256 public constant STREAM_AMOUNT_GHO = 400_000 ether;
  uint256 public constant STREAM_END = 1731405179;

  function execute() external {
    uint256 duration = STREAM_END - block.timestamp;
    uint256 exactAmount = (STREAM_AMOUNT_GHO / duration) * duration;
    
    // ... stream creation code
  }
```

With this change the stream will be exact at time of execution & **slightly less** then 400k ether due to rounding(maximum 1 second of emission -1 is lost on the rounding).
Calculated based on current block would be th like `399999999999999982988448`

2024-04-19 14:20 UTC, sakulstra approved these changes

2024-04-21 17:21 UTC, rustboyar approved these changes

2024-04-22 07:53 UTC, merged