feat: aave v1 deprecation phase 3
bgd-labs/aave-proposals-v3 pull request #327
Opened 2024-05-02 14:30 UTC by sakulstra

2024-05-02 14:31 UTC, sakulstra commented on src/20240218_AaveV1Ethereum_AaveV1DeprecationPhase2/config.ts
>      pools: ['AaveV1Ethereum'],
it changed because i used the config to generate the new one

2024-05-02 14:31 UTC, sakulstra commented on generator/templates/proposal.template.ts
> +  const poolName = /AaveV[2|3](.*)/.test(pool) && pool.match(/AaveV[2|3](.*)/)![1];
is changed to allow creation of proposal without an attached pool

2024-05-03 08:09 UTC, kyzia551 requested changes

2024-05-03 08:09 UTC, kyzia551 commented on src/20240502_AaveV1Ethereum_AaveV1Deprecation/AaveV1Ethereum_AaveV1Deprecation_20240502.t.sol
> +      // offboarding liquidations should provide a fixed 1% bonus
```suggestion
      // offboarding liquidations should provide a fixed 5% bonus
```

2024-05-03 08:09 UTC, kyzia551 commented on src/20240502_AaveV1Ethereum_AaveV1Deprecation/AaveV1Ethereum_AaveV1Deprecation_20240502.t.sol
> +      assertEq(liquidityRateAfter, 0);
please add to this test, that currentStableBorrowRate and currentVariableBorrowRate also 0

2024-05-03 13:55 UTC, kyzia551 approved these changes

2024-05-04 09:39 UTC, merged