Orbit program renewal may 2024
bgd-labs/aave-proposals-v3 pull request #338
Opened 2024-05-13 22:36 UTC by Rozengarden

2024-05-24 10:31 UTC, marczeller reviewed
added snapshots links

2024-05-24 10:31 UTC, marczeller commented on src/20240513_AaveV3Ethereum_OrbitProgramRenewal/OrbitProgramRenewal.md
> +snapshot: "TODO"
```suggestion
snapshot:"https://snapshot.org/#/aave.eth/proposal/0x4a10e2a8ca95024d7cf0791aa82ed262c816ff0ee78bc2f3ab3487e70d731361"
```

2024-05-24 10:31 UTC, marczeller commented on src/20240513_AaveV3Ethereum_OrbitProgramRenewal/config.ts
> +    snapshot: 'TODO',
```suggestion
    snapshot: 'https://snapshot.org/#/aave.eth/proposal/0x4a10e2a8ca95024d7cf0791aa82ed262c816ff0ee78bc2f3ab3487e70d731361',
```

2024-05-24 10:31 UTC, marczeller commented on src/20240513_AaveV3Ethereum_OrbitProgramRenewal/AaveV3Ethereum_OrbitProgramRenewal_20240513.sol
> + * - Snapshot: TODO
```suggestion
 * - Snapshot: "https://snapshot.org/#/aave.eth/proposal/0x4a10e2a8ca95024d7cf0791aa82ed262c816ff0ee78bc2f3ab3487e70d731361"
```

2024-05-28 13:12 UTC, kyzia551 requested changes

2024-05-28 16:32 UTC, marczeller commented on src/20240513_AaveV3Ethereum_OrbitProgramRenewal/OrbitProgramRenewal.md
> +- [Snapshot](TODO)
```suggestion
- [Snapshot](https://snapshot.org/#/aave.eth/proposal/0x4a10e2a8ca95024d7cf0791aa82ed262c816ff0ee78bc2f3ab3487e70d731361)
```

2024-05-28 16:36 UTC, kyzia551 submitted a review, later dismissed

2024-05-30 09:54 UTC, rustboyar submitted a review, later dismissed

2024-05-30 10:12 UTC, rustboyar commented on src/20240513_AaveV3Ethereum_OrbitProgramRenewal/OrbitProgramRenewal.md
> +snapshot:"https://snapshot.org/#/aave.eth/proposal/0x4a10e2a8ca95024d7cf0791aa82ed262c816ff0ee78bc2f3ab3487e70d731361"
```suggestion
snapshot: "https://snapshot.org/#/aave.eth/proposal/0x4a10e2a8ca95024d7cf0791aa82ed262c816ff0ee78bc2f3ab3487e70d731361"
```

2024-05-30 11:03 UTC, rustboyar approved these changes

2024-05-30 11:32 UTC, rustboyar approved these changes

2024-05-30 11:32 UTC, merged