Add AIP for V4 AL Service Provider Proposal
bgd-labs/aave-proposals-v3 pull request #357
Opened 2024-06-15 00:37 UTC by CheyenneAtapour

https://governance.aave.com/t/temp-check-service-provider-proposal/17866

2024-06-21 11:00 UTC, miguelmtzinf requested changes

2024-06-21 16:39 UTC, CheyenneAtapour commented on src/20240614_AaveV3Ethereum_V4ALServiceProviderProposal/AaveV3Ethereum_V4ALServiceProviderProposal_20240614.sol
> +    (GHO_STREAM_AMOUNT / GHO_STREAM_DURATION) * GHO_STREAM_DURATION;
It ensures there are no rounding errors with the stream by ensuring the dollar amount is divisible by seconds. I saw the same was done here: https://github.com/bgd-labs/aave-proposals-v3/pull/331/files#diff-19fff750e1e69bf557e3608c28b57945f6b0cfdc33b99b4988c4494a2de10ce6R23

2024-06-21 17:14 UTC, CheyenneAtapour commented on src/20240614_AaveV3Ethereum_V4ALServiceProviderProposal/AaveV3Ethereum_V4ALServiceProviderProposal_20240614.t.sol
> +
done

2024-06-21 17:14 UTC, CheyenneAtapour commented on src/20240614_AaveV3Ethereum_V4ALServiceProviderProposal/AaveV3Ethereum_V4ALServiceProviderProposal_20240614.sol
> +  address public constant AAVE_LABS = 0xac140648435d03f784879cd789130F22Ef588Fcd;
done

2024-06-24 10:42 UTC, miguelmtzinf commented on src/20240614_AaveV3Ethereum_V4ALServiceProviderProposal/AaveV3Ethereum_V4ALServiceProviderProposal_20240614.sol
> + * - Discussion: https://governance.aave.com/t/temp-check-service-provider-proposal/17866
Update these two:
https://snapshot.org/#/aave.eth/proposal/0x70dfd865b78c4c391e2b0729b907d152e6e8a0da683416d617d8f84782036349
https://governance.aave.com/t/arfc-al-service-provider-proposal/17974

2024-06-24 10:45 UTC, miguelmtzinf commented on src/20240614_AaveV3Ethereum_V4ALServiceProviderProposal/AaveV3Ethereum_V4ALServiceProviderProposal_20240614.t.sol
> +    vm.prank(0x1a88Df1cFe15Af22B3c4c783D4e6F7F9e0C1885d);
can we just use `deal`?

2024-06-24 10:46 UTC, miguelmtzinf commented on src/20240614_AaveV3Ethereum_V4ALServiceProviderProposal/config.ts
> +    snapshot:
update

2024-06-24 17:52 UTC, CheyenneAtapour commented on src/20240614_AaveV3Ethereum_V4ALServiceProviderProposal/AaveV3Ethereum_V4ALServiceProviderProposal_20240614.sol
> + * - Discussion: https://governance.aave.com/t/temp-check-service-provider-proposal/17866
done

2024-06-24 17:52 UTC, CheyenneAtapour commented on src/20240614_AaveV3Ethereum_V4ALServiceProviderProposal/AaveV3Ethereum_V4ALServiceProviderProposal_20240614.t.sol
> +    vm.prank(0x1a88Df1cFe15Af22B3c4c783D4e6F7F9e0C1885d);
done

2024-06-24 17:52 UTC, CheyenneAtapour commented on src/20240614_AaveV3Ethereum_V4ALServiceProviderProposal/config.ts
> +    snapshot:
done

2024-06-25 09:18 UTC, sakulstra submitted a review, later dismissed

2024-06-25 09:28 UTC, sendra commented on src/20240614_AaveV3Ethereum_V4ALServiceProviderProposal/V4ALServiceProviderProposal.md
> +title: "[ARFC] AL Service Provider Proposal"
No need to put ARFC in the title

2024-06-25 09:34 UTC, sendra commented on src/20240614_AaveV3Ethereum_V4ALServiceProviderProposal/V4ALServiceProviderProposal.md
> +This ARFC proposes a one-year technical contributor engagement for the Aave Labs to act as a service provider for development of Aave V4 and a new visual identity.
This is the AIP not ARFC

2024-06-25 09:35 UTC, sendra commented on src/20240614_AaveV3Ethereum_V4ALServiceProviderProposal/V4ALServiceProviderProposal.md
> +The text of this ARFC is released under the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/). The visuals and the New Visual identity are subject to and governed by the license speci
AIP

2024-06-25 23:50 UTC, sendra commented on src/20240614_AaveV3Ethereum_V4ALServiceProviderProposal/V4ALServiceProviderProposal.md
> +The text of this AIP is released under the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/). The visuals and the New Visual identity are subject to and governed by the license specif
```suggestion
The text of this AIP is released under the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/). The visuals and the New Visual identity are subject to and governed by the license specified in the approved governance proposal by the Aave DAO.
```

2024-06-26 07:12 UTC, sendra approved these changes

2024-06-26 11:46 UTC, merged