[aavechan] IR curve update for stable
bgd-labs/aave-proposals-v3 pull request #380
Opened 2024-07-14 21:03 UTC by Rozengarden

2024-07-15 13:22 UTC, kyzia551 requested changes

2024-07-15 13:53 UTC, Rozengarden commented on diffs/AaveV2Ethereum_StablecoinIRCurveAmendment_20240714_before_AaveV2Ethereum_StablecoinIRCurveAmendment_20240714_after.md
which part wasn't mentioned ?

2024-07-18 07:24 UTC, kyzia551 commented on diffs/AaveV2Ethereum_StablecoinIRCurveAmendment_20240714_before_AaveV2Ethereum_StablecoinIRCurveAmendment_20240714_after.md
ok, it seems I was blind, sorry

2024-07-18 07:25 UTC, kyzia551 approved these changes

2024-07-18 17:38 UTC, eboadom approved these changes

2024-07-18 17:38 UTC, merged