feat: zkSync activation
bgd-labs/aave-proposals-v3 pull request #422
Opened 2024-08-09 11:23 UTC by brotherlymite

2024-08-14 09:04 UTC, eboadom commented on zksync/src/20240805_AaveV3ZkSync_AaveV3ZkSyncActivation/AaveV3ZkSync_AaveV3ZkSyncActivation_20240805.t.sol
> +    executePayload(vm, address(proposal));
Why not doing this all together? Only executing payload once. It is more correct as all funds should be there

2024-08-16 07:51 UTC, eboadom submitted a review, later dismissed

2024-08-16 11:00 UTC, sakulstra requested changes

2024-08-16 11:04 UTC, sakulstra submitted a review, later dismissed

2024-08-16 13:34 UTC, eboadom approved these changes

2024-08-16 13:35 UTC, merged