feat: stream ChaosLabs payment
bgd-labs/aave-proposals-v3 pull request #485
Opened 2024-10-12 22:01 UTC by Rozengarden

2024-10-14 03:33 UTC, brotherlymite commented on src/20241012_AaveV3Ethereum_ChaosLabsAaveRiskManagementServiceRenewal/ChaosLabsAaveRiskManagementServiceRenewal.md
> +- [Snapshot](TODO)
```suggestion
- Snapshot: Direct to AIP
```

2024-10-14 03:43 UTC, brotherlymite commented on src/20241012_AaveV3Ethereum_ChaosLabsAaveRiskManagementServiceRenewal/AaveV3Ethereum_ChaosLabsAaveRiskManagementServiceRenewal_20241012.sol
> + * - Snapshot: TODO
```suggestion
 * - Snapshot: Direct To AIP
```

2024-10-14 03:43 UTC, brotherlymite commented on src/20241012_AaveV3Ethereum_ChaosLabsAaveRiskManagementServiceRenewal/AaveV3Ethereum_ChaosLabsAaveRiskManagementServiceRenewal_20241012.sol
> +import {IERC20} from 'solidity-utils/contracts/oz-common/interfaces/IERC20.sol';
```suggestion
```

2024-10-14 03:50 UTC, brotherlymite commented on src/20241012_AaveV3Ethereum_ChaosLabsAaveRiskManagementServiceRenewal/AaveV3Ethereum_ChaosLabsAaveRiskManagementServiceRenewal_20241012.sol
> +        amount: 1_000_000 ether,
@Rozengarden aUSDC has 6 decimals so we should not use ether here.

2024-10-14 03:52 UTC, brotherlymite commented on src/20241012_AaveV3Ethereum_ChaosLabsAaveRiskManagementServiceRenewal/AaveV3Ethereum_ChaosLabsAaveRiskManagementServiceRenewal_20241012.t.sol
> +  function test_defaultProposalExecution() public {
@Rozengarden I would also add that test that we can withdraw the whole amount after 1 year

2024-10-14 04:39 UTC, Rozengarden commented on src/20241012_AaveV3Ethereum_ChaosLabsAaveRiskManagementServiceRenewal/ChaosLabsAaveRiskManagementServiceRenewal.md
> +- [Snapshot](TODO)
Snapshot will be posted in a few hours

2024-10-14 18:54 UTC, ianflexa approved these changes

2024-10-15 12:26 UTC, ianflexa commented on src/20241012_AaveV3Ethereum_ChaosLabsAaveRiskManagementServiceRenewal/ChaosLabsAaveRiskManagementServiceRenewal.md
> +![Screenshot 2024-09-27 at 15.50.34|1408x1710](upload://Aqu3IuxgoK2aEjL54oW9WkwpmnG)
```suggestion

```

2024-10-15 12:28 UTC, ianflexa requested changes

2024-10-15 12:28 UTC, ianflexa commented on src/20241012_AaveV3Ethereum_ChaosLabsAaveRiskManagementServiceRenewal/ChaosLabsAaveRiskManagementServiceRenewal.md
> +![Screenshot 2024-09-27 at 15.50.34|1408x1710](upload://Aqu3IuxgoK2aEjL54oW9WkwpmnG)
```suggestion

```

2024-10-15 12:40 UTC, ianflexa submitted a review, later dismissed

2024-10-16 13:04 UTC, brotherlymite commented
@Rozengarden could you fix lint as CI is failing otherwise

2024-10-17 05:03 UTC, brotherlymite approved these changes

2024-10-17 07:20 UTC, merged